# Generated by Django 4.0.5 on 2022-06-05 20:34

from django.db import migrations, models
import django.utils.timezone
import hindex.happiness_levels.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HappinessLevel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(help_text='Level one to ten. One means unhappiest, ten means happiest', validators=[hindex.happiness_levels.validators.validate_level_limit])),
                ('factor', models.CharField(choices=[('Health', 'Health'), ('Financial Situation', 'Financial'), ('Family Relationships', 'Family'), ('Work', 'Work'), ('Community and Friends', 'Friends'), ('Personal Value', 'Personal'), ('Personal Freedom', 'Freedom'), ('Other', 'Other')], max_length=256)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for happiness level factor', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
